"""Initial migration

Revision ID: a6823fb7a97a
Revises: 
Create Date: 2024-11-10 14:09:32.526511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6823fb7a97a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('avatar',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('surname',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
